table 'Version History'
	isHidden
	lineageTag: b2cf47ef-46ce-4d08-b3b8-ac19dbd89d73

	column Version
		dataType: string
		lineageTag: 72489407-cfd4-467d-86e4-dec76ee9ccd3
		summarizeBy: none
		sourceColumn: Version

		annotation SummarizationSetBy = Automatic

	column Timestamp
		dataType: dateTime
		formatString: General Date
		lineageTag: c845862a-b4d4-4ed2-a08c-355e8908b956
		summarizeBy: none
		sourceColumn: Timestamp

		variation Variation
			isDefault
			relationship: 93924ef9-a6f4-4e9f-be18-b5b7e962f2b9
			defaultHierarchy: LocalDateTable_80c23bf5-c966-4a5a-859e-8e1c97220560.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Comment
		dataType: string
		lineageTag: 56cd80d2-9ec5-42a3-ae69-e5422b0582ac
		summarizeBy: none
		sourceColumn: Comment

		annotation SummarizationSetBy = Automatic

	partition 'Version History-89982c3c-aadd-4f6b-b601-4b829faa9582' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("Tcu9CsIwEADgVzkyl+ZytX/ZxMVFcC8dQhNqoL1IUoW8vRYVnD++YRBYqhJFIQhVIxVKqkGhrnpNPRwvb/DsN28WeLqYfGAxFnuiv6QkdkCaOl21cN2PsdZZOJnNzSFmOHsXTZxu+ZurX24lNpL2XDeaDp+8BusWzzNMizP8uINhCylz4LwmMY4v", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type text) meta [Serialized.Text = true]) in type table [Version = _t, Timestamp = _t, Comment = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Version", type text}, {"Timestamp", type datetime}, {"Comment", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

